name: DEV - Deploy Static Web Apps

on:
  push:
    branches:
      - deploy-dev

  workflow_dispatch:
    inputs:
      job_to_run:
        description: "Run deploy manually"
        required: true
        type: choice
        options:
          - deploy-dev

permissions:
  contents: read
  actions: read

jobs:
  deploy:
    # Run if branch is deploy-dev OR manual workflow_dispatch selecting deploy-dev
    if: github.ref == 'refs/heads/deploy-dev' || inputs.job_to_run == 'deploy-dev'
    runs-on: ubuntu-latest

    steps:

      - name: Create apps folder
        run: mkdir -p apps

      # -----------------------------
      # Download latest Climate Change artifact
      # -----------------------------
      - name: Download latest Climate Change artifact
        run: |
          RUN_ID=$(gh run list \
            --repo ${{ github.repository }} \
            --workflow "DEV - Build Climate Change" \
            --status success \
            --limit 1 \
            --json databaseId \
            --jq '.[0].databaseId')

          if [ -z "$RUN_ID" ]; then
            echo "No successful Climate Change build found"
            exit 1
          fi

          echo "Downloading Climate Change artifact from run: $RUN_ID"

          gh run download $RUN_ID \
            --repo ${{ github.repository }} \
            -n climate-change-app \
            -D apps/climate-change
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          
      # -----------------------------
      # Download latest SLR artifact
      # -----------------------------
      - name: Download latest SLR artifact
        run: |
          RUN_ID=$(gh run list \
            --repo ${{ github.repository }} \
            --workflow "DEV - Build SLR" \
            --status success \
            --limit 1 \
            --json databaseId \
            --jq '.[0].databaseId')

          gh run download $RUN_ID \
            --repo ${{ github.repository }} \
            -n slr-app \
            -D apps/slr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repo
        uses: actions/checkout@v4


      # -----------------------------
      # Deploy combined apps folder to Azure
      # -----------------------------
      - name: Deploy to Azure Static Web App (DEV)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_APPS_DEV_TOKEN }}
          action: upload
          app_location: apps
          output_location: ""
